#!/bin/bash

echo "took data"
COMMIT_HASH=$(git log -1 --format=format:%H)
COMMIT_MESSAGE=$(git log -1 --pretty=%B)
AUTHOR=$(git log -1 --pretty=format:'%an')
TIMESTAMP=$(date +%s)

# send data to the local running web server
curl -X POST http://127.0.0.1:5000/git-commit \
     -H "Content-Type: application/json" \
     -d "{\"commit_hash\": \"$COMMIT_HASH\", \"commit_message\": \"$COMMIT_MESSAGE\", \"author\": \"$AUTHOR\", \"timestamp\": \"$TIMESTAMP\"}"

echo "data sent to server"